# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- azure-pipelines

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.16.1'
  displayName: 'Install Node.js'

- script: yarn install
  displayName: yarn install

- script: npx run react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/'
  displayName: bundle android

- task: Gradle@2
  inputs:
    workingDirectory: 'android'
    gradleWrapperFile: 'android/gradlew'
    tasks: 'assembleRelease'
  continueOnError: false

- script: mv android/app/build/outputs/apk/release/app-release-unsigned.apk app-release.apk
  displayName: Android Postprocess
  continueOnError: false
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'my-upload-key.keystore'
  displayName: 'Download Keystore file'
  
- task: AndroidSigning@3
  inputs:
    apkFiles: 'app-release.apk'
    apksign: true
    apksignerKeystoreFile: 'my-upload-key.keystore'
    apksignerKeystorePassword: '$(KEYSTORE_PASSWORD)'
    apksignerKeystoreAlias: 'my-key-alias'
    apksignerKeyPassword: '$(KEYSTORE_PASSWORD)'
  displayName: 'Signing Android Release APK'