trigger:
  branches:
    include:
    - azure-pipelines

pool:
  vmImage: 'macOS-10.15'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.16.1'
  displayName: 'Install Node.js'

- script: yarn install
  displayName: 'Install dependencies'

- script: npm run android-build-release
  displayName: 'Android | Bundle and build'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'my-upload-key.keystore'
  displayName: 'Android | Download keystore file'

- task: AndroidSigning@3
  inputs:
    apkFiles: 'android/app/build/outputs/apk/release/*.apk'
    apksign: true # Optional
    apksignerKeystoreFile: 'my-upload-key.keystore'
    apksignerKeystorePassword: '$(KEYSTORE_PASSWORD)'
    apksignerKeystoreAlias: 'my-key-alias'
    apksignerKeyPassword: '$(KEYSTORE_PASSWORD)'
  displayName: 'Android | Signing release APK'

# Copy to Gless server
- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: '$(FTP_SERVER)'
    username: '$(FTP_USER)'
    password: '$(FTP_PASSWORD)'
    rootDirectory: 'android/app/build/outputs/apk/release/'
    filePatterns: '*.apk'
    remoteDirectory: '/downloads/android/'
    enableUtf8: true
    clean: false
    cleanContents: false
    preservePaths: true
    trustSSL: true
  displayName: Android | Copy APK to Gless server'