# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.16.1'
  displayName: 'Install Node.js'

- script: |
    npm install yarn
    yarn
  displayName: 'Install dependencies'

- script: |
    npm run android-build-release
  displayName: 'Bundle Android Release'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'my-upload-key.keystore'
  displayName: 'Download Keystore file'

- task: AndroidSigning@3
  inputs:
    apkFiles: 'android/app/build/outputs/apk/release/*.apk'
    apksignerKeystoreFile: 'my-upload-key.keystore'
    apksignerKeystorePassword: '$(KEYSTORE_PASSWORD)'
    apksignerKeystoreAlias: 'my-key-alias'
    apksignerKeyPassword: '$(KEYSTORE_PASSWORD)'
  displayName: 'Signing Android Release APK'